version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]

networks:
  web:
    external: true
  internal:
    external: false

services:

    moodle:
      ports: ["8081:8080"]
      image: docker.io/bitnami/moodle:4
      restart: unless-stopped
      environment:
        - TZ=Europe/Paris
        - MOODLE_DATABASE_HOST=mariadb
        - MOODLE_DATABASE_PORT_NUMBER=3306
        - MOODLE_DATABASE_USER=bn_moodle
        - MOODLE_DATABASE_NAME=bitnami_moodle
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - 'moodle_data:/bitnami/moodle'
        - 'moodledata_data:/bitnami/moodledata'
      networks:
        - internal
        - web
      depends_on:
        - mariadb
      labels:
          - "traefik.enable=true"
          - "traefik.port=8080"
          - "traefik.http.routers.moodle.rule=Host(`salouma.ddns.net`)"
          - "traefik.http.routers.moodle.entrypoints=websecure"
          - "traefik.docker.network=web"

    mariadb:
      image: docker.io/bitnami/mariadb:10.5
      restart: unless-stopped
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_USER=bn_moodle
        - MARIADB_DATABASE=bitnami_moodle
        - MARIADB_CHARACTER_SET=utf8mb4
        - MARIADB_COLLATE=utf8mb4_unicode_ci
      networks:
          - internal
      volumes:
        - 'mariadb_data:/bitnami/mariadb'
    
    orthanc:
        image: osimis/orthanc:21.1.7
        container_name: orthanc
        restart: unless-stopped
        ports: ["8042:8042"]
        volumes: 
          - orthanc:/var/lib/orthanc/db:Z
        networks:
          - internal
          - web
        environment:
            ORTHANC__AUTHENTICATION_ENABLED: "false"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"
        labels:
          - "traefik.enable=true"
          - "traefik.port=8042"
          - "traefik.http.routers.orthanc.rule=Host(`salouma.ddns.net`) && PathPrefix(`/dicom-web/`)"
          - "traefik.http.routers.orthanc.entrypoints=websecure"
          - "traefik.docker.network=web"

volumes:
    moodle_data:
    moodledata_data:
    orthanc:
    orthancpacs:
    orthanctoolsjs:
    mariadb_data:
