version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]

networks:
  web:
    external: true
  internal:
    external: false

services:

    moodle:
      ports: ["8081:8080"]
      image: docker.io/bitnami/moodle:4
      restart: unless-stopped
      environment:
        - TZ=Europe/Paris
        - MOODLE_DATABASE_HOST=mariadb
        - MOODLE_DATABASE_PORT_NUMBER=3306
        - MOODLE_DATABASE_USER=bn_moodle
        - MOODLE_DATABASE_NAME=bitnami_moodle
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - 'moodle_data:/bitnami/moodle'
        - 'moodledata_data:/bitnami/moodledata'
      networks:
        - internal
        - web
      depends_on:
        - mariadb
      labels:
          - "traefik.enable=true"
          - "traefik.port=8080"
          - "traefik.docker.network=web"
          - "traefik.http.routers.moodle.entrypoints=web"
          - "traefik.http.routers.moodle.rule=Host(`localhost`)"

    mariadb:
      image: docker.io/bitnami/mariadb:10.5
      restart: unless-stopped
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_USER=bn_moodle
        - MARIADB_DATABASE=bitnami_moodle
        - MARIADB_CHARACTER_SET=utf8mb4
        - MARIADB_COLLATE=utf8mb4_unicode_ci
      networks:
          - internal
      volumes:
        - 'mariadb_data:/bitnami/mariadb'
    
volumes:
    moodle_data:
    moodledata_data:
    mariadb_data:
