# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Creation of the dicomviewer folder
      run : mkdir dicomviewer
      working-directory: /tmp
    - name: Copy temporary dicomviewer folder
      run : |
        mv ./* /tmp/dicomviewer
        mv /tmp/dicomviewer ./
    - name: Doowload Stone Of Orthanc Distribution
      run: |
        mkdir stone
        cd stone
        wget https://lsb.orthanc-server.com/stone-webviewer/2.3/wasm-binaries.zip
        unzip wasm-binaries.zip -d .
        rm wasm-binaries.zip
      working-directory: /tmp
    - name: copy Temporary stone of Orthanc Build to Distribution
      run : mv /tmp/stone/wasm-binaries/StoneWebViewer/* ./dicomviewer/viewer-stone
    - name: build OHIF Distribution
      run: |
        mkdir ohif
        cd ohif
        git clone --depth 1 --branch @ohif/viewer@4.9.21 https://github.com/OHIF/Viewers.git
        cd Viewers
        yarn install
        QUICK_BUILD=true PUBLIC_URL=/mod/dicomviewer/viewer-ohif/ yarn run build
      working-directory: /tmp
    - name: copy Temporary OHIF build to Distribution
      run : mv /tmp/ohif/Viewers/platform/viewer/dist/* ./dicomviewer/viewer-ohif
    - name: OHIF Replace configuration and index file
      run : mv ./dicomviewer/config-ohif/* ./dicomviewer/viewer-ohif
    - name: STONE Replace configuration file
      run : mv ./dicomviewer/config-stone/* ./dicomviewer/viewer-stone
    - name: Deleting files .git
      run : |
        rm -rf ./.git
        rm -rf ./.github
        rm -f ./.gitignore
        rm -rf ./dicomviewer/Documentation
    - uses: actions/upload-artifact@v1
      with:
        name: dicomviewer
        path: ./

