# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Build checkout'
      uses: actions/checkout@v4

    - name: Creation of the dicomviewer folder
      run : mkdir dicomviewer
      working-directory: /tmp
    - name: Copy temporary dicomviewer folder
      run : |
        mv ./* /tmp/dicomviewer
        mv /tmp/dicomviewer ./
    - name: Download Stone Of Orthanc Distribution
      run: |
        mkdir stone
        cd stone
        wget https://orthanc.uclouvain.be/downloads/linux-standard-base/stone-web-viewer/2.3/wasm-binaries.zip
        unzip wasm-binaries.zip -d .
        rm wasm-binaries.zip
      working-directory: /tmp
    - name: copy Temporary stone of Orthanc Build to Distribution
      run : mv /tmp/stone/wasm-binaries/StoneWebViewer/* ./dicomviewer/viewer-stone
    - name: build OHIF Distribution
      run: |
        mkdir ohif
        cd ohif
        git clone --depth 1 --branch v3.7.0 https://github.com/OHIF/Viewers.git
        cd Viewers && yarn config set workspaces-experimental true && yarn install && QUICK_BUILD=true PUBLIC_URL=/mod/dicomviewer/viewer-ohif/ yarn run build
      working-directory: /tmp
    - name: copy Temporary OHIF build to Distribution
      run : mv /tmp/ohif/Viewers/platform/app/dist/* ./dicomviewer/viewer-ohif
    - name: OHIF Replace configuration and index file
      run : mv ./dicomviewer/config-ohif/* ./dicomviewer/viewer-ohif
    - name: STONE Replace configuration file
      run : mv ./dicomviewer/config-stone/* ./dicomviewer/viewer-stone
    - name: Deleting files .git
      run : |
        rm -rf ./.git
        rm -rf ./.github
        rm -f ./.gitignore
        rm -rf ./dicomviewer/Documentation
    - uses: actions/upload-artifact@v4
      with:
        name: dicomviewer
        path: ./

